import 'package:cts_underground_mining_assessment/data/models/inspection_enums.dart';
import 'package:cts_underground_mining_assessment/features/pdf_report/pdf_report_models.dart';
import 'package:flutter_test/flutter_test.dart';

import '../support/spec_fixtures.dart';

void main() {
  test(
    'clean pass fixture produces a complete, unflagged report snapshot',
    () async {
      final service = await createService();
      final inspection = await seedCleanPass(service);
      final report = toReportData(inspection);
      expect(report.status, InspectionReportStatus.complete);
      expect(report.flaggedItemCount, 0);
      expect(report.allPhotos.length, 0);
      expect(report.signature, isNotNull);
      expect(report.actionItems, isEmpty);
      expect(report.statusLabel, 'Complete');
    },
  );

  test(
    'at risk, unsatisfactory, and critical fixtures carry the expected counts',
    () async {
      final service = await createService();
      final atRisk = toReportData(await seedAtRisk(service));
      final unsatisfactory = toReportData(await seedUnsatisfactory(service));
      final critical = toReportData(await seedCritical(service));

      expect(atRisk.flaggedItemCount, 1);
      expect(atRisk.atRiskCount, 1);
      expect(atRisk.unsatisfactoryCount, 0);
      expect(atRisk.criticalCount, 0);

      expect(unsatisfactory.flaggedItemCount, 1);
      expect(unsatisfactory.unsatisfactoryCount, 1);
      expect(unsatisfactory.actionItems, hasLength(2));

      expect(critical.flaggedItemCount, 1);
      expect(critical.criticalCount, 1);
      expect(critical.criticalAcknowledged, isTrue);
      expect(critical.actionItems, hasLength(2));
    },
  );

  test(
    'many photos and hose replacement fixtures preserve media and action detail',
    () async {
      final service = await createService();
      final manyPhotos = toReportData(await seedManyPhotos(service));
      final hoseReplacement = await seedHoseReplacement(service);

      expect(manyPhotos.allPhotos.length, 10);
      expect(manyPhotos.allPhotos, hasLength(10));
      expect(manyPhotos.sections.first.items.first.label, 'HPU Wide Shot');

      expect(hoseReplacement.hoseEntries, hasLength(1));
      expect(hoseReplacement.actionItems, hasLength(1));
      expect(hoseReplacement.actionItems.single.isAutoGenerated, isTrue);
      expect(hoseReplacement.actionItems.single.partsRequired, 'H-334, F-221');
    },
  );

  test(
    'exported and imported inspection stays searchable and keeps restored files',
    () async {
      final service = await createService();
      final source = await seedExportImport(service);
      final bundle = await service.exportInspection(source);
      final imported = await service.importInspection(bundle);

      expect(service.search(source.workOrderNumber), contains(source));
      expect(service.search(imported.documentNumber), contains(imported));
      expect(imported.photos.length, 1);
      expect(imported.generatedPdfPath, isNotNull);
      expect(imported.status, InspectionStatus.complete);
    },
  );
}
