import 'dart:convert';

import 'package:cts_underground_mining_assessment/data/models/inspection_enums.dart';

class SpecValidationIssue {
  const SpecValidationIssue({required this.fieldKey, required this.message});

  final String fieldKey;
  final String message;
}

class SpecValidationResult {
  const SpecValidationResult(this.issues);

  final List<SpecValidationIssue> issues;

  bool get isComplete => issues.isEmpty;
}

class SpecResponse {
  const SpecResponse({
    required this.sectionKey,
    required this.itemKey,
    required this.itemLabel,
    required this.fieldType,
    required this.value,
    required this.isRequired,
    this.conditionRating,
    this.comment,
  });

  final String sectionKey;
  final String itemKey;
  final String itemLabel;
  final InspectionFieldType fieldType;
  final String value;
  final bool isRequired;
  final ConditionRating? conditionRating;
  final String? comment;

  bool get isFlagged => conditionRating?.isFlagged ?? false;

  Map<String, Object?> toJson() => <String, Object?>{
    'sectionKey': sectionKey,
    'itemKey': itemKey,
    'itemLabel': itemLabel,
    'fieldType': fieldType.value,
    'value': value,
    'isRequired': isRequired,
    'conditionRating': conditionRating?.value,
    'comment': comment,
  };

  factory SpecResponse.fromJson(Map<String, Object?> json) {
    return SpecResponse(
      sectionKey: json['sectionKey']! as String,
      itemKey: json['itemKey']! as String,
      itemLabel: json['itemLabel']! as String,
      fieldType: InspectionFieldTypeX.fromValue(json['fieldType']! as String),
      value: json['value']! as String,
      isRequired: json['isRequired']! as bool,
      conditionRating: json['conditionRating'] == null
          ? null
          : ConditionRatingX.fromValue(json['conditionRating']! as String),
      comment: json['comment'] as String?,
    );
  }
}

class SpecPhoto {
  const SpecPhoto({
    required this.id,
    required this.sectionKey,
    required this.itemKey,
    required this.filePath,
    required this.caption,
    required this.sortOrder,
    required this.capturedAt,
  });

  final String id;
  final String sectionKey;
  final String itemKey;
  final String filePath;
  final String caption;
  final int sortOrder;
  final DateTime capturedAt;

  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'sectionKey': sectionKey,
    'itemKey': itemKey,
    'filePath': filePath,
    'caption': caption,
    'sortOrder': sortOrder,
    'capturedAt': capturedAt.toIso8601String(),
  };

  factory SpecPhoto.fromJson(Map<String, Object?> json) {
    return SpecPhoto(
      id: json['id']! as String,
      sectionKey: json['sectionKey']! as String,
      itemKey: json['itemKey']! as String,
      filePath: json['filePath']! as String,
      caption: json['caption']! as String,
      sortOrder: json['sortOrder']! as int,
      capturedAt: DateTime.parse(json['capturedAt']! as String),
    );
  }
}

class SpecActionItem {
  const SpecActionItem({
    required this.id,
    required this.sourceSectionKey,
    required this.sourceItemKey,
    required this.conditionRating,
    required this.title,
    required this.description,
    required this.isAutoGenerated,
    this.partsRequired,
  });

  final String id;
  final String sourceSectionKey;
  final String sourceItemKey;
  final ConditionRating? conditionRating;
  final String title;
  final String description;
  final bool isAutoGenerated;
  final String? partsRequired;

  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'sourceSectionKey': sourceSectionKey,
    'sourceItemKey': sourceItemKey,
    'conditionRating': conditionRating?.value,
    'title': title,
    'description': description,
    'isAutoGenerated': isAutoGenerated,
    'partsRequired': partsRequired,
  };

  factory SpecActionItem.fromJson(Map<String, Object?> json) {
    return SpecActionItem(
      id: json['id']! as String,
      sourceSectionKey: json['sourceSectionKey']! as String,
      sourceItemKey: json['sourceItemKey']! as String,
      conditionRating: json['conditionRating'] == null
          ? null
          : ConditionRatingX.fromValue(json['conditionRating']! as String),
      title: json['title']! as String,
      description: json['description']! as String,
      isAutoGenerated: json['isAutoGenerated']! as bool,
      partsRequired: json['partsRequired'] as String?,
    );
  }
}

class SpecHoseEntry {
  const SpecHoseEntry({
    required this.id,
    required this.hoseNameLocation,
    required this.failureType,
    required this.hoseSize,
    required this.hoseLength,
    required this.hoseType,
    required this.fittingEndA,
    required this.fittingEndB,
    required this.quantity,
    required this.replacementPartNumbers,
    required this.partsNeeded,
    required this.notes,
  });

  final String id;
  final String hoseNameLocation;
  final FailureType? failureType;
  final String hoseSize;
  final String hoseLength;
  final String hoseType;
  final String fittingEndA;
  final String fittingEndB;
  final int quantity;
  final String replacementPartNumbers;
  final String partsNeeded;
  final String notes;

  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'hoseNameLocation': hoseNameLocation,
    'failureType': failureType?.value,
    'hoseSize': hoseSize,
    'hoseLength': hoseLength,
    'hoseType': hoseType,
    'fittingEndA': fittingEndA,
    'fittingEndB': fittingEndB,
    'quantity': quantity,
    'replacementPartNumbers': replacementPartNumbers,
    'partsNeeded': partsNeeded,
    'notes': notes,
  };

  factory SpecHoseEntry.fromJson(Map<String, Object?> json) {
    return SpecHoseEntry(
      id: json['id']! as String,
      hoseNameLocation: json['hoseNameLocation']! as String,
      failureType: json['failureType'] == null
          ? null
          : FailureTypeX.fromValue(json['failureType']! as String),
      hoseSize: json['hoseSize']! as String,
      hoseLength: json['hoseLength']! as String,
      hoseType: json['hoseType']! as String,
      fittingEndA: json['fittingEndA']! as String,
      fittingEndB: json['fittingEndB']! as String,
      quantity: json['quantity']! as int,
      replacementPartNumbers: json['replacementPartNumbers']! as String,
      partsNeeded: json['partsNeeded']! as String,
      notes: json['notes']! as String,
    );
  }
}

class SpecInspection {
  SpecInspection({
    required this.id,
    required this.documentNumber,
    required this.status,
    required this.customer,
    required this.workOrderNumber,
    required this.customerReference,
    required this.assetName,
    required this.siteLocation,
    required this.technicianName,
    required this.servicingShop,
    required this.inspectionDateTime,
    required this.createdAt,
    required this.updatedAt,
    this.completedAt,
    this.emailedAt,
    this.finalTechComments,
    this.signatureFilePath,
    this.generatedPdfPath,
    this.criticalAcknowledged = false,
    List<SpecResponse>? responses,
    List<SpecPhoto>? photos,
    List<SpecActionItem>? actionItems,
    List<SpecHoseEntry>? hoseEntries,
  }) : responses = responses ?? <SpecResponse>[],
       photos = photos ?? <SpecPhoto>[],
       actionItems = actionItems ?? <SpecActionItem>[],
       hoseEntries = hoseEntries ?? <SpecHoseEntry>[];

  final String id;
  String documentNumber;
  InspectionStatus status;
  String customer;
  String workOrderNumber;
  String customerReference;
  String assetName;
  String siteLocation;
  String technicianName;
  String servicingShop;
  DateTime inspectionDateTime;
  DateTime createdAt;
  DateTime updatedAt;
  DateTime? completedAt;
  DateTime? emailedAt;
  String? finalTechComments;
  String? signatureFilePath;
  String? generatedPdfPath;
  bool criticalAcknowledged;
  final List<SpecResponse> responses;
  final List<SpecPhoto> photos;
  final List<SpecActionItem> actionItems;
  final List<SpecHoseEntry> hoseEntries;

  bool get hasProgress =>
      responses.isNotEmpty ||
      photos.isNotEmpty ||
      actionItems.isNotEmpty ||
      hoseEntries.isNotEmpty ||
      (finalTechComments != null && finalTechComments!.trim().isNotEmpty) ||
      signatureFilePath != null;

  Map<String, Object?> toJson() => <String, Object?>{
    'id': id,
    'documentNumber': documentNumber,
    'status': status.value,
    'customer': customer,
    'workOrderNumber': workOrderNumber,
    'customerReference': customerReference,
    'assetName': assetName,
    'siteLocation': siteLocation,
    'technicianName': technicianName,
    'servicingShop': servicingShop,
    'inspectionDateTime': inspectionDateTime.toIso8601String(),
    'createdAt': createdAt.toIso8601String(),
    'updatedAt': updatedAt.toIso8601String(),
    'completedAt': completedAt?.toIso8601String(),
    'emailedAt': emailedAt?.toIso8601String(),
    'finalTechComments': finalTechComments,
    'signatureFilePath': signatureFilePath,
    'generatedPdfPath': generatedPdfPath,
    'criticalAcknowledged': criticalAcknowledged,
    'responses': responses.map((SpecResponse e) => e.toJson()).toList(),
    'photos': photos.map((SpecPhoto e) => e.toJson()).toList(),
    'actionItems': actionItems.map((SpecActionItem e) => e.toJson()).toList(),
    'hoseEntries': hoseEntries.map((SpecHoseEntry e) => e.toJson()).toList(),
  };

  factory SpecInspection.fromJson(Map<String, Object?> json) {
    return SpecInspection(
      id: json['id']! as String,
      documentNumber: json['documentNumber']! as String,
      status: InspectionStatusX.fromValue(json['status']! as String),
      customer: json['customer']! as String,
      workOrderNumber: json['workOrderNumber']! as String,
      customerReference: json['customerReference']! as String,
      assetName: json['assetName']! as String,
      siteLocation: json['siteLocation']! as String,
      technicianName: json['technicianName']! as String,
      servicingShop: json['servicingShop']! as String,
      inspectionDateTime: DateTime.parse(json['inspectionDateTime']! as String),
      createdAt: DateTime.parse(json['createdAt']! as String),
      updatedAt: DateTime.parse(json['updatedAt']! as String),
      completedAt: json['completedAt'] == null
          ? null
          : DateTime.parse(json['completedAt']! as String),
      emailedAt: json['emailedAt'] == null
          ? null
          : DateTime.parse(json['emailedAt']! as String),
      finalTechComments: json['finalTechComments'] as String?,
      signatureFilePath: json['signatureFilePath'] as String?,
      generatedPdfPath: json['generatedPdfPath'] as String?,
      criticalAcknowledged: json['criticalAcknowledged']! as bool,
      responses: (json['responses']! as List<dynamic>)
          .cast<Map<String, Object?>>()
          .map(SpecResponse.fromJson)
          .toList(),
      photos: (json['photos']! as List<dynamic>)
          .cast<Map<String, Object?>>()
          .map(SpecPhoto.fromJson)
          .toList(),
      actionItems: (json['actionItems']! as List<dynamic>)
          .cast<Map<String, Object?>>()
          .map(SpecActionItem.fromJson)
          .toList(),
      hoseEntries: (json['hoseEntries']! as List<dynamic>)
          .cast<Map<String, Object?>>()
          .map(SpecHoseEntry.fromJson)
          .toList(),
    );
  }
}

String encodeSpecJson(Object? value) => jsonEncode(value);

Map<String, Object?> decodeSpecJson(String value) =>
    jsonDecode(value) as Map<String, Object?>;
