import 'package:flutter/material.dart';

import 'constants.dart';
import '../data/models/inspection_enums.dart';

class DashboardMetric {
  const DashboardMetric({
    required this.label,
    required this.value,
    required this.icon,
    required this.color,
    required this.subtitle,
  });

  final String label;
  final String value;
  final IconData icon;
  final Color color;
  final String subtitle;
}

class InspectionPhotoView {
  const InspectionPhotoView({
    required this.assetPath,
    required this.caption,
    required this.sectionTitle,
    required this.itemLabel,
    required this.capturedAt,
  });

  final String assetPath;
  final String caption;
  final String sectionTitle;
  final String itemLabel;
  final DateTime capturedAt;
}

class InspectionActionItemView {
  const InspectionActionItemView({
    required this.title,
    required this.description,
    required this.conditionRating,
    required this.sourceSection,
    required this.sourceItem,
    this.partsRequired,
    this.isAutoGenerated = true,
  });

  final String title;
  final String description;
  final ConditionRating conditionRating;
  final String sourceSection;
  final String sourceItem;
  final String? partsRequired;
  final bool isAutoGenerated;
}

class InspectionSectionView {
  const InspectionSectionView({
    required this.key,
    required this.title,
    required this.completionState,
    required this.summary,
    required this.photoCount,
    this.flaggedCount = 0,
    this.criticalWarning = false,
  });

  final String key;
  final String title;
  final SectionCompletionState completionState;
  final String summary;
  final int photoCount;
  final int flaggedCount;
  final bool criticalWarning;
}

class InspectionSummary {
  InspectionSummary({
    required this.id,
    required this.documentNumber,
    required this.customer,
    required this.workOrderNumber,
    required this.customerReference,
    required this.assetName,
    required this.siteLocation,
    required this.technicianName,
    required this.servicingShop,
    required this.inspectionDateTime,
    required this.createdAt,
    required this.status,
    required this.sections,
    required this.actionItems,
    required this.photos,
    required this.flaggedCount,
    required this.atRiskCount,
    required this.unsatisfactoryCount,
    required this.criticalCount,
    required this.photoCount,
    required this.lastUpdatedAt,
    this.completedAt,
    this.emailedAt,
    this.finalTechComments,
    this.criticalAcknowledged = false,
    this.generatedPdfPath,
  });

  final String id;
  final String documentNumber;
  final String customer;
  final String workOrderNumber;
  final String customerReference;
  final String assetName;
  final String siteLocation;
  final String technicianName;
  final String servicingShop;
  final DateTime inspectionDateTime;
  final DateTime createdAt;
  final InspectionStatus status;
  final List<InspectionSectionView> sections;
  final List<InspectionActionItemView> actionItems;
  final List<InspectionPhotoView> photos;
  final int flaggedCount;
  final int atRiskCount;
  final int unsatisfactoryCount;
  final int criticalCount;
  final int photoCount;
  final DateTime lastUpdatedAt;
  final DateTime? completedAt;
  final DateTime? emailedAt;
  final String? finalTechComments;
  final bool criticalAcknowledged;
  final String? generatedPdfPath;

  String get statusLabel => status.label;

  String get searchableText => [
    documentNumber,
    customer,
    workOrderNumber,
    customerReference,
    assetName,
    siteLocation,
    technicianName,
    servicingShop,
    status.label,
  ].join(' ').toLowerCase();

  InspectionSummary copyWith({
    String? id,
    String? documentNumber,
    String? customer,
    String? workOrderNumber,
    String? customerReference,
    String? assetName,
    String? siteLocation,
    String? technicianName,
    String? servicingShop,
    DateTime? inspectionDateTime,
    DateTime? createdAt,
    InspectionStatus? status,
    List<InspectionSectionView>? sections,
    List<InspectionActionItemView>? actionItems,
    List<InspectionPhotoView>? photos,
    int? flaggedCount,
    int? atRiskCount,
    int? unsatisfactoryCount,
    int? criticalCount,
    int? photoCount,
    DateTime? lastUpdatedAt,
    DateTime? completedAt,
    DateTime? emailedAt,
    String? finalTechComments,
    bool? criticalAcknowledged,
    String? generatedPdfPath,
  }) {
    return InspectionSummary(
      id: id ?? this.id,
      documentNumber: documentNumber ?? this.documentNumber,
      customer: customer ?? this.customer,
      workOrderNumber: workOrderNumber ?? this.workOrderNumber,
      customerReference: customerReference ?? this.customerReference,
      assetName: assetName ?? this.assetName,
      siteLocation: siteLocation ?? this.siteLocation,
      technicianName: technicianName ?? this.technicianName,
      servicingShop: servicingShop ?? this.servicingShop,
      inspectionDateTime: inspectionDateTime ?? this.inspectionDateTime,
      createdAt: createdAt ?? this.createdAt,
      status: status ?? this.status,
      sections: sections ?? this.sections,
      actionItems: actionItems ?? this.actionItems,
      photos: photos ?? this.photos,
      flaggedCount: flaggedCount ?? this.flaggedCount,
      atRiskCount: atRiskCount ?? this.atRiskCount,
      unsatisfactoryCount: unsatisfactoryCount ?? this.unsatisfactoryCount,
      criticalCount: criticalCount ?? this.criticalCount,
      photoCount: photoCount ?? this.photoCount,
      lastUpdatedAt: lastUpdatedAt ?? this.lastUpdatedAt,
      completedAt: completedAt ?? this.completedAt,
      emailedAt: emailedAt ?? this.emailedAt,
      finalTechComments: finalTechComments ?? this.finalTechComments,
      criticalAcknowledged: criticalAcknowledged ?? this.criticalAcknowledged,
      generatedPdfPath: generatedPdfPath ?? this.generatedPdfPath,
    );
  }
}

class WorkspaceSearchScope {
  const WorkspaceSearchScope({required this.label, this.status});

  final String label;
  final InspectionStatus? status;
}

const workspaceSearchScopes = <WorkspaceSearchScope>[
  WorkspaceSearchScope(label: 'All'),
  WorkspaceSearchScope(label: 'Draft', status: InspectionStatus.draft),
  WorkspaceSearchScope(
    label: 'In Progress',
    status: InspectionStatus.inProgress,
  ),
  WorkspaceSearchScope(label: 'Complete', status: InspectionStatus.complete),
  WorkspaceSearchScope(label: 'Emailed', status: InspectionStatus.emailed),
];

const inspectionSectionTitles = <String, String>{
  InspectionSectionKeys.jobAssetIdentification: 'Job & Asset Identification',
  InspectionSectionKeys.componentTracking: 'Component Tracking',
  InspectionSectionKeys.fluidTankService: 'Fluid & Tank Service',
  InspectionSectionKeys.hoseConnectionInspection:
      'Hose & Connection Inspection',
  InspectionSectionKeys.filtrationBreatherService:
      'Filtration & Breather Service',
  InspectionSectionKeys.operationalDataSystemTest:
      'Operational Data / System Test',
  InspectionSectionKeys.followUpRepairsQuoting: 'Follow-Up Repairs & Quoting',
  InspectionSectionKeys.reviewCompletion: 'Review & Completion',
};
