import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../core/theme.dart';
import '../../core/workspace_models.dart';
import '../../core/workspace_providers.dart';
import '../../widgets/section_card.dart';
import '../../widgets/status_badge.dart';
import '../../widgets/signature_pad.dart';

class ActionItemsScreen extends ConsumerWidget {
  const ActionItemsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final controller = ref.watch(workspaceProvider);
    final items = controller.openActionItems;
    return SingleChildScrollView(
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SectionCard(
            title: 'Action Items',
            subtitle:
                'Auto-generated and manual follow-up work tracked locally.',
            child: Wrap(
              spacing: 12,
              runSpacing: 12,
              children: [
                StatusChip(
                  text: '${items.length} open items',
                  color: CtsPalette.info,
                ),
                const StatusChip(
                  text: 'No required priority field in V1',
                  color: CtsPalette.slate,
                ),
                const StatusChip(
                  text: 'Auto-linked to flagged inspection items',
                  color: CtsPalette.orange,
                ),
              ],
            ),
          ),
          const SizedBox(height: 18),
          LayoutBuilder(
            builder: (context, constraints) {
              final wide = constraints.maxWidth >= 1180;
              return wide
                  ? Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Expanded(child: _ActionList(items: items)),
                        const SizedBox(width: 18),
                        const SizedBox(width: 360, child: _ActionSummary()),
                      ],
                    )
                  : Column(
                      children: [
                        _ActionList(items: items),
                        const SizedBox(height: 18),
                        const _ActionSummary(),
                      ],
                    );
            },
          ),
        ],
      ),
    );
  }
}

class _ActionList extends StatelessWidget {
  const _ActionList({required this.items});

  final List<InspectionActionItemView> items;

  @override
  Widget build(BuildContext context) {
    return SectionCard(
      title: 'Open Action Items',
      subtitle: items.isEmpty
          ? 'No action items are currently open.'
          : '${items.length} items tracked across inspections',
      child: Column(
        children: [
          if (items.isEmpty)
            _EmptyState(
              icon: Icons.task_alt_outlined,
              title: 'No open work',
              body:
                  'Action items generated from flagged items will appear here.',
            )
          else
            for (final item in items) ...[
              _ActionCard(item: item),
              if (item != items.last) const SizedBox(height: 12),
            ],
        ],
      ),
    );
  }
}

class _ActionCard extends StatelessWidget {
  const _ActionCard({required this.item});

  final InspectionActionItemView item;

  @override
  Widget build(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Expanded(
                  child: Text(
                    item.title,
                    style: Theme.of(context).textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.w700,
                    ),
                  ),
                ),
                StatusBadge.forCondition(item.conditionRating),
              ],
            ),
            const SizedBox(height: 8),
            Text(
              item.description,
              style: Theme.of(context).textTheme.bodyMedium,
            ),
            const SizedBox(height: 10),
            Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                _Tag(
                  text: item.sourceSection,
                  icon: Icons.view_agenda_outlined,
                ),
                _Tag(text: item.sourceItem, icon: Icons.label_outline),
                if (item.partsRequired != null)
                  _Tag(
                    text: item.partsRequired!,
                    icon: Icons.construction_outlined,
                  ),
                if (item.isAutoGenerated)
                  const _Tag(text: 'Auto-generated', icon: Icons.auto_fix_high),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _Tag extends StatelessWidget {
  const _Tag({required this.text, required this.icon});

  final String text;
  final IconData icon;

  @override
  Widget build(BuildContext context) {
    return Chip(
      avatar: Icon(icon, size: 18, color: CtsPalette.orange),
      label: Text(text),
    );
  }
}

class _ActionSummary extends StatelessWidget {
  const _ActionSummary();

  @override
  Widget build(BuildContext context) {
    return SectionCard(
      title: 'Summary',
      subtitle: 'The action summary stays visible beside the work list.',
      child: Column(
        children: const [
          _SummaryRow(
            label: 'Auto-generated actions',
            value: 'Linked to flagged responses',
          ),
          SizedBox(height: 10),
          _SummaryRow(
            label: 'Manual actions',
            value: 'Editable by the technician',
          ),
          SizedBox(height: 10),
          _SummaryRow(
            label: 'Source records',
            value: 'Inspection detail and PDF',
          ),
        ],
      ),
    );
  }
}

class _SummaryRow extends StatelessWidget {
  const _SummaryRow({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Row(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        SizedBox(
          width: 110,
          child: Text(
            label,
            style: Theme.of(context).textTheme.labelLarge?.copyWith(
              color: Theme.of(context).colorScheme.onSurfaceVariant,
            ),
          ),
        ),
        Expanded(
          child: Text(
            value,
            style: Theme.of(
              context,
            ).textTheme.bodyMedium?.copyWith(fontWeight: FontWeight.w600),
          ),
        ),
      ],
    );
  }
}

class _EmptyState extends StatelessWidget {
  const _EmptyState({
    required this.icon,
    required this.title,
    required this.body,
  });

  final IconData icon;
  final String title;
  final String body;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(18),
      decoration: BoxDecoration(
        color: Theme.of(context).colorScheme.surfaceContainerHighest,
        borderRadius: BorderRadius.circular(18),
      ),
      child: Row(
        children: [
          Container(
            width: 44,
            height: 44,
            decoration: BoxDecoration(
              color: CtsPalette.success.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(14),
            ),
            child: Icon(icon, color: CtsPalette.success),
          ),
          const SizedBox(width: 12),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  title,
                  style: Theme.of(
                    context,
                  ).textTheme.titleSmall?.copyWith(fontWeight: FontWeight.w700),
                ),
                const SizedBox(height: 4),
                Text(
                  body,
                  style: Theme.of(context).textTheme.bodySmall?.copyWith(
                    color: Theme.of(context).colorScheme.onSurfaceVariant,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
