import 'package:cts_underground_mining_assessment/core/constants.dart';
import 'package:cts_underground_mining_assessment/core/validators.dart';
import 'package:cts_underground_mining_assessment/data/models/inspection_enums.dart';
import 'package:cts_underground_mining_assessment/data/models/inspection_models.dart';
import 'package:flutter_test/flutter_test.dart';

import '../support/persistence_test_helpers.dart';

void main() {
  test('completion passes when required fields and signoff are present', () {
    final inspection = buildInspection(
      id: 'inspection-1',
      documentNumber: '20260420-0001',
      status: InspectionStatus.inProgress,
    );
    fillRequiredResponses(inspection);
    inspection.signatureFilePath = '/tmp/signature.png';
    inspection.completedAt = DateTime.utc(2026, 4, 20, 12, 30);

    final result = InspectionValidator.validateForCompletion(inspection);

    expect(result.isValid, isTrue);
  });

  test('flagged responses require comment photo and action item', () {
    final inspection = buildInspection(
      id: 'inspection-2',
      documentNumber: '20260420-0002',
      status: InspectionStatus.inProgress,
    );
    fillRequiredResponses(inspection);
    inspection.signatureFilePath = '/tmp/signature.png';
    inspection.completedAt = DateTime.utc(2026, 4, 20, 12, 30);
    inspection.responses = inspection.responses
        .map(
          (response) => response.itemKey == InspectionItemKeys.tankIntegrity
              ? InspectionResponse(
                  id: response.id,
                  inspectionId: response.inspectionId,
                  sectionKey: response.sectionKey,
                  itemKey: response.itemKey,
                  itemLabel: response.itemLabel,
                  fieldType: response.fieldType,
                  value: ConditionRating.monitorAtRisk.value,
                  conditionRating: ConditionRating.monitorAtRisk,
                  isFlagged: true,
                  comment: null,
                  createdAt: response.createdAt,
                  updatedAt: response.updatedAt,
                )
              : response,
        )
        .toList(growable: false);

    final result = InspectionValidator.validateForCompletion(inspection);

    expect(result.isValid, isFalse);
    expect(
      result.issues.map((issue) => issue.message),
      contains('Tank Integrity requires a comment.'),
    );
    expect(
      result.issues.map((issue) => issue.message),
      contains('Tank Integrity requires at least one photo.'),
    );
    expect(
      result.issues.map((issue) => issue.message),
      contains('Tank Integrity requires a linked action item.'),
    );
  });

  test('critical responses require LOTO acknowledgement', () {
    final inspection = buildInspection(
      id: 'inspection-3',
      documentNumber: '20260420-0003',
      status: InspectionStatus.inProgress,
    );
    fillRequiredResponses(inspection);
    inspection.signatureFilePath = '/tmp/signature.png';
    inspection.completedAt = DateTime.utc(2026, 4, 20, 12, 30);
    inspection.criticalAcknowledged = false;
    inspection.responses = inspection.responses
        .map(
          (response) => response.itemKey == InspectionItemKeys.tankIntegrity
              ? InspectionResponse(
                  id: response.id,
                  inspectionId: response.inspectionId,
                  sectionKey: response.sectionKey,
                  itemKey: response.itemKey,
                  itemLabel: response.itemLabel,
                  fieldType: response.fieldType,
                  value: ConditionRating.criticalOutOfService.value,
                  conditionRating: ConditionRating.criticalOutOfService,
                  isFlagged: true,
                  comment: 'Severe damage.',
                  createdAt: response.createdAt,
                  updatedAt: response.updatedAt,
                )
              : response,
        )
        .toList(growable: false);
    inspection.photos.add(
      InspectionPhoto(
        id: 'photo-1',
        inspectionId: inspection.id,
        sectionKey: InspectionSectionKeys.fluidTankService,
        itemKey: InspectionItemKeys.tankIntegrity,
        filePath: '/tmp/photo.jpg',
        caption: 'Damage',
        sortOrder: 0,
        capturedAt: DateTime.utc(2026, 4, 20, 12, 0),
        createdAt: DateTime.utc(2026, 4, 20, 12, 0),
      ),
    );
    inspection.actionItems.add(
      ActionItem(
        id: 'action-1',
        inspectionId: inspection.id,
        sourceSectionKey: InspectionSectionKeys.fluidTankService,
        sourceItemKey: InspectionItemKeys.tankIntegrity,
        conditionRating: ConditionRating.criticalOutOfService,
        title: 'Tank Integrity requires attention',
        description: 'Severe damage.',
        isAutoGenerated: true,
        createdAt: DateTime.utc(2026, 4, 20, 12, 0),
        updatedAt: DateTime.utc(2026, 4, 20, 12, 0),
      ),
    );

    final result = InspectionValidator.validateForCompletion(inspection);

    expect(result.isValid, isFalse);
    expect(
      result.issues.map((issue) => issue.message),
      contains(AppConstants.lotOWarning),
    );
  });
}
