import 'dart:typed_data';

import 'package:cts_underground_mining_assessment/features/pdf_report/pdf_report_models.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('report models aggregate counts and flagged items correctly', () {
    final report = InspectionReportData(
      documentNumber: '20260418-0001',
      customer: 'Acme Manufacturing',
      workOrderNumber: 'WO-48158',
      customerReference: 'PO-1194',
      assetName: 'HPU-13',
      siteLocation: 'Main Plant',
      technicianName: 'Jordan Lee',
      servicingShop: 'CTS North Shop',
      inspectionDateTime: DateTime.utc(2026, 4, 18, 17, 40),
      createdAt: DateTime.utc(2026, 4, 18, 17, 41),
      status: InspectionReportStatus.complete,
      completedAt: DateTime.utc(2026, 4, 18, 18, 0),
      criticalAcknowledged: true,
      signature: InspectionReportSignature(
        bytes: Uint8List.fromList(<int>[1, 2, 3, 4]),
        signerName: 'Jordan Lee',
        signedAt: DateTime.utc(2026, 4, 18, 18, 0),
      ),
      sections: <InspectionReportSection>[
        InspectionReportSection(
          key: 'fluid',
          title: 'Fluid & Tank Service',
          items: <InspectionReportItem>[
            InspectionReportItem(
              label: 'Fluid Level',
              value: 'Within Tolerance',
              conditionRating: ReportConditionRating.satisfactory,
            ),
            InspectionReportItem(
              label: 'Tank Integrity',
              value: 'Seepage',
              conditionRating: ReportConditionRating.unsatisfactory,
              comment: 'Visible seepage at seam.',
              photos: <InspectionReportPhoto>[
                InspectionReportPhoto(
                  bytes: Uint8List.fromList(<int>[5, 6, 7, 8]),
                  caption: 'Tank seam',
                  sectionTitle: 'Fluid & Tank Service',
                  itemLabel: 'Tank Integrity',
                ),
              ],
            ),
          ],
        ),
      ],
      actionItems: <InspectionReportActionItem>[
        InspectionReportActionItem(
          title: 'Tank Integrity requires attention',
          description: 'Visible seepage at seam.',
          conditionRating: ReportConditionRating.unsatisfactory,
          isAutoGenerated: true,
        ),
      ],
      branding: const InspectionReportBranding(
        companyName: 'Combined Technical Services',
        logoAssetPath: 'assets/logo/cts_logo.png',
      ),
    );

    expect(report.statusLabel, 'Complete');
    expect(report.totalItemCount, 2);
    expect(report.flaggedItemCount, 1);
    expect(report.atRiskCount, 0);
    expect(report.unsatisfactoryCount, 1);
    expect(report.criticalCount, 0);
    expect(report.photoCount, 1);
    expect(report.flaggedItems.single.label, 'Tank Integrity');
    expect(report.flaggedItems.single.isFlagged, isTrue);
    expect(report.allPhotos.single.itemLabel, 'Tank Integrity');
    expect(report.allPhotos.single.caption, 'Tank seam');
  });

  test('condition rating labels stay customer-facing and readable', () {
    expect(ReportConditionRating.satisfactory.label, 'Satisfactory');
    expect(ReportConditionRating.monitor.label, 'Monitor / At Risk');
    expect(ReportConditionRating.unsatisfactory.label, 'Unsatisfactory');
    expect(ReportConditionRating.critical.label, 'Critical / Out of Service');
    expect(ReportConditionRating.monitor.isFlagged, isTrue);
    expect(ReportConditionRating.satisfactory.isFlagged, isFalse);
  });
}
