import 'dart:io';

import 'package:cts_underground_mining_assessment/core/constants.dart';
import 'package:cts_underground_mining_assessment/data/models/inspection_enums.dart';
import 'package:flutter_test/flutter_test.dart';

import '../support/spec_fixtures.dart';
import '../support/spec_models.dart';
import '../support/spec_service.dart';

void main() {
  test('document numbers follow YYYYMMDD-0001 and never reuse numbers', () {
    final generator = SpecDocumentNumberGenerator();
    expect(generator.next(DateTime.utc(2026, 4, 18)), '20260418-0001');
    expect(generator.next(DateTime.utc(2026, 4, 18)), '20260418-0002');
    expect(generator.next(DateTime.utc(2026, 4, 19)), '20260419-0001');
  });

  test(
    'validation blocks completion until flagged items satisfy comment photo and action rules',
    () async {
      final service = await createService();
      final inspection = service.createInspection(
        now: DateTime.utc(2026, 4, 18, 15, 0),
        customer: 'Acme Manufacturing',
        workOrderNumber: 'WO-5001',
        customerReference: 'PO-1',
        assetName: 'HPU',
        siteLocation: 'Plant 1',
        technicianName: 'Jordan Lee',
        servicingShop: 'CTS North Shop',
      );
      service.upsertResponse(
        inspection: inspection,
        sectionKey: InspectionSectionKeys.fluidTankService,
        itemKey: InspectionItemKeys.tankIntegrity,
        itemLabel: 'Tank Integrity',
        fieldType: InspectionFieldType.conditionRating,
        value: ConditionRating.criticalOutOfService.value,
        isRequired: true,
        conditionRating: ConditionRating.criticalOutOfService,
      );
      final firstValidation = service.validateCompletion(inspection);
      expect(firstValidation.isComplete, isFalse);
      expect(
        firstValidation.issues.map(
          (SpecValidationIssue issue) => issue.fieldKey,
        ),
        containsAll(<String>[
          'fluid_tank_service.tank_integrity.comment',
          'fluid_tank_service.tank_integrity.photos',
          'fluid_tank_service.tank_integrity.criticalAck',
          'signature',
        ]),
      );

      service.upsertResponse(
        inspection: inspection,
        sectionKey: InspectionSectionKeys.fluidTankService,
        itemKey: InspectionItemKeys.tankIntegrity,
        itemLabel: 'Tank Integrity',
        fieldType: InspectionFieldType.conditionRating,
        value: ConditionRating.criticalOutOfService.value,
        isRequired: true,
        conditionRating: ConditionRating.criticalOutOfService,
        comment: 'Visible damage.',
      );
      await service.addPhoto(
        inspection: inspection,
        sectionKey: InspectionSectionKeys.fluidTankService,
        itemKey: InspectionItemKeys.tankIntegrity,
        caption: 'Damage',
      );
      service.addManualActionItem(
        inspection: inspection,
        sourceSectionKey: InspectionSectionKeys.fluidTankService,
        sourceItemKey: InspectionItemKeys.tankIntegrity,
        conditionRating: ConditionRating.criticalOutOfService,
        title: 'Tank Integrity requires attention',
        description: 'Visible damage.',
      );
      inspection.criticalAcknowledged = true;
      inspection.signatureFilePath = '/tmp/signature.png';
      final completeValidation = service.validateCompletion(inspection);
      expect(completeValidation.isComplete, isTrue);
      expect(
        service.completeInspection(inspection).status,
        InspectionStatus.complete,
      );
    },
  );

  test(
    'flagged responses create auto actions and clear them when returned to satisfactory',
    () async {
      final service = await createService();
      final inspection = service.createInspection(
        now: DateTime.utc(2026, 4, 18, 16, 0),
        customer: 'Acme Manufacturing',
        workOrderNumber: 'WO-5002',
        customerReference: 'PO-2',
        assetName: 'HPU',
        siteLocation: 'Plant 1',
        technicianName: 'Jordan Lee',
        servicingShop: 'CTS North Shop',
      );
      service.upsertResponse(
        inspection: inspection,
        sectionKey: InspectionSectionKeys.hoseConnectionInspection,
        itemKey: InspectionItemKeys.overallHoseCondition,
        itemLabel: 'Overall Hose Condition',
        fieldType: InspectionFieldType.conditionRating,
        value: ConditionRating.monitorAtRisk.value,
        isRequired: true,
        conditionRating: ConditionRating.monitorAtRisk,
        comment: 'Minor abrasion.',
      );
      expect(inspection.actionItems, hasLength(1));
      expect(inspection.actionItems.single.isAutoGenerated, isTrue);
      expect(
        inspection.actionItems.single.sourceItemKey,
        InspectionItemKeys.overallHoseCondition,
      );

      service.upsertResponse(
        inspection: inspection,
        sectionKey: InspectionSectionKeys.hoseConnectionInspection,
        itemKey: InspectionItemKeys.overallHoseCondition,
        itemLabel: 'Overall Hose Condition',
        fieldType: InspectionFieldType.conditionRating,
        value: ConditionRating.satisfactory.value,
        isRequired: true,
        conditionRating: ConditionRating.satisfactory,
      );
      expect(inspection.actionItems, isEmpty);
    },
  );

  test(
    'photo fake service enforces max photos and preserves ordering',
    () async {
      final service = await createService();
      final inspection = service.createInspection(
        now: DateTime.utc(2026, 4, 18, 17, 0),
        customer: 'Acme Manufacturing',
        workOrderNumber: 'WO-5003',
        customerReference: 'PO-3',
        assetName: 'HPU',
        siteLocation: 'Plant 1',
        technicianName: 'Jordan Lee',
        servicingShop: 'CTS North Shop',
      );
      for (var i = 0; i < AppConstants.maxPhotosPerInspectionItem; i++) {
        await service.addPhoto(
          inspection: inspection,
          sectionKey: InspectionSectionKeys.jobAssetIdentification,
          itemKey: InspectionItemKeys.overviewPhotos,
          caption: 'Photo $i',
        );
      }
      expect(
        () => service.addPhoto(
          inspection: inspection,
          sectionKey: InspectionSectionKeys.jobAssetIdentification,
          itemKey: InspectionItemKeys.overviewPhotos,
          caption: 'Overflow',
        ),
        throwsStateError,
      );
      service.reorderPhotos(
        inspection,
        sectionKey: InspectionSectionKeys.jobAssetIdentification,
        itemKey: InspectionItemKeys.overviewPhotos,
        orderedPhotoIds: inspection.photos.reversed
            .map((SpecPhoto photo) => photo.id)
            .toList(),
      );
      expect(inspection.photos.first.caption, 'Photo 9');
      service.deletePhoto(inspection, inspection.photos.first.id);
      expect(inspection.photos, hasLength(9));
    },
  );

  test(
    'duplicate, email, search, export, and import follow the local-only rules',
    () async {
      final service = await createService();
      final source = await seedExportImport(service);

      final duplicate = service.duplicateInspection(source);
      expect(duplicate.documentNumber, isNot(source.documentNumber));
      expect(duplicate.customer, source.customer);
      expect(duplicate.photos, isEmpty);
      expect(duplicate.signatureFilePath, isNull);
      expect(duplicate.completedAt, isNull);
      expect(duplicate.status, InspectionStatus.draft);

      service.markEmailed(
        source,
        confirmed: true,
        recipient: 'customer@example.com',
        customer: 'Acme Manufacturing',
      );
      expect(source.status, InspectionStatus.emailed);
      expect(source.emailedAt, isNotNull);
      expect(service.recentRecipientUsage()['customer@example.com'], 1);
      expect(
        service.recentRecipientCustomers()['customer@example.com'],
        'Acme Manufacturing',
      );

      final byWorkOrder = service.search('WO-48158');
      expect(byWorkOrder, contains(source));
      expect(service.search('Acme Manufacturing'), contains(source));
      expect(service.search(source.documentNumber), contains(source));
      expect(
        service.search('Jordan Lee', scope: InspectionSearchScope.emailed),
        contains(source),
      );

      final pdfFile = await service.generatePdf(source);
      expect(await pdfFile.exists(), isTrue);
      expect(await pdfFile.length(), greaterThan(0));

      final bundle = await service.exportInspection(source);
      expect(await bundle.exists(), isTrue);
      final imported = await service.importInspection(bundle);
      expect(imported.documentNumber, isNot(source.documentNumber));
      expect(imported.photos, isNotEmpty);
      expect(imported.generatedPdfPath, isNotNull);
      expect(await File(imported.photos.first.filePath).exists(), isTrue);
      expect(await File(imported.generatedPdfPath!).exists(), isTrue);

      final conflictBundle = await service.exportInspection(source);
      final conflictImport = await service.importInspection(conflictBundle);
      expect(conflictImport.documentNumber, isNot(source.documentNumber));

      final edited = service.editAfterEmail(source, (SpecInspection draft) {
        draft.customer = 'Acme Manufacturing Updated';
      });
      expect(edited.emailedAt, isNull);
      expect(edited.status, InspectionStatus.complete);

      final second = await seedExportImport(service);
      service.markEmailed(
        second,
        confirmed: true,
        recipient: 'other@example.com',
        customer: 'Acme Manufacturing',
      );
      final invalidated = service.editAfterEmail(second, (
        SpecInspection draft,
      ) {
        draft.signatureFilePath = null;
      });
      expect(invalidated.emailedAt, isNull);
      expect(invalidated.status, InspectionStatus.inProgress);
    },
  );
}
