import 'dart:typed_data';

enum InspectionReportStatus { draft, inProgress, complete, emailed }

extension InspectionReportStatusLabel on InspectionReportStatus {
  String get label {
    switch (this) {
      case InspectionReportStatus.draft:
        return 'Draft';
      case InspectionReportStatus.inProgress:
        return 'In Progress';
      case InspectionReportStatus.complete:
        return 'Complete';
      case InspectionReportStatus.emailed:
        return 'Emailed';
    }
  }
}

enum ReportConditionRating { satisfactory, monitor, unsatisfactory, critical }

extension ReportConditionRatingLabel on ReportConditionRating {
  String get label {
    switch (this) {
      case ReportConditionRating.satisfactory:
        return 'Good';
      case ReportConditionRating.monitor:
        return 'Fair';
      case ReportConditionRating.unsatisfactory:
        return 'Poor';
      case ReportConditionRating.critical:
        return 'Critical / Out of Service';
    }
  }

  bool get isFlagged =>
      this == ReportConditionRating.monitor ||
      this == ReportConditionRating.unsatisfactory ||
      this == ReportConditionRating.critical;
}

class InspectionReportBranding {
  const InspectionReportBranding({
    this.companyName = 'Combined Technical Services',
    this.logoAssetPath,
    this.logoBytes,
  });

  final String companyName;
  final String? logoAssetPath;
  final Uint8List? logoBytes;
}

class InspectionReportPhoto {
  const InspectionReportPhoto({
    this.filePath,
    this.bytes,
    required this.caption,
    required this.sectionTitle,
    required this.itemLabel,
    this.capturedAt,
    this.sortOrder = 0,
  }) : assert(
         filePath != null || bytes != null,
         'A photo needs a filePath or bytes.',
       );

  final String? filePath;
  final Uint8List? bytes;
  final String caption;
  final String sectionTitle;
  final String itemLabel;
  final DateTime? capturedAt;
  final int sortOrder;
}

class InspectionReportSignature {
  const InspectionReportSignature({
    this.filePath,
    this.bytes,
    required this.signerName,
    required this.signedAt,
  }) : assert(
         filePath != null || bytes != null,
         'A signature needs a filePath or bytes.',
       );

  final String? filePath;
  final Uint8List? bytes;
  final String signerName;
  final DateTime signedAt;
}

class InspectionReportActionItem {
  const InspectionReportActionItem({
    required this.title,
    required this.description,
    this.sourceSection,
    this.sourceItem,
    this.partsRequired,
    this.isAutoGenerated = false,
    this.conditionRating,
  });

  final String title;
  final String description;
  final String? sourceSection;
  final String? sourceItem;
  final String? partsRequired;
  final bool isAutoGenerated;
  final ReportConditionRating? conditionRating;
}

class InspectionReportItem {
  const InspectionReportItem({
    required this.label,
    required this.value,
    this.conditionRating,
    this.comment,
    this.photos = const <InspectionReportPhoto>[],
    this.helperText,
    this.tags = const <String>[],
  });

  final String label;
  final String value;
  final ReportConditionRating? conditionRating;
  final String? comment;
  final List<InspectionReportPhoto> photos;
  final String? helperText;
  final List<String> tags;

  bool get isFlagged => conditionRating?.isFlagged ?? false;
}

class InspectionReportSection {
  const InspectionReportSection({
    required this.key,
    required this.title,
    this.subtitle,
    this.items = const <InspectionReportItem>[],
  });

  final String key;
  final String title;
  final String? subtitle;
  final List<InspectionReportItem> items;
}

class InspectionReportData {
  const InspectionReportData({
    required this.documentNumber,
    required this.customer,
    required this.workOrderNumber,
    required this.customerReference,
    required this.assetName,
    required this.siteLocation,
    required this.technicianName,
    required this.servicingShop,
    required this.inspectionDateTime,
    required this.createdAt,
    required this.status,
    required this.sections,
    this.completedAt,
    this.emailedAt,
    this.finalTechComments,
    this.criticalAcknowledged = false,
    this.signature,
    this.actionItems = const <InspectionReportActionItem>[],
    this.branding = const InspectionReportBranding(),
  });

  final String documentNumber;
  final String customer;
  final String workOrderNumber;
  final String customerReference;
  final String assetName;
  final String siteLocation;
  final String technicianName;
  final String servicingShop;
  final DateTime inspectionDateTime;
  final DateTime createdAt;
  final DateTime? completedAt;
  final DateTime? emailedAt;
  final InspectionReportStatus status;
  final String? finalTechComments;
  final bool criticalAcknowledged;
  final InspectionReportSignature? signature;
  final List<InspectionReportSection> sections;
  final List<InspectionReportActionItem> actionItems;
  final InspectionReportBranding branding;

  Iterable<InspectionReportItem> get allItems =>
      sections.expand((section) => section.items);

  List<InspectionReportItem> get flaggedItems =>
      allItems.where((item) => item.isFlagged).toList(growable: false);

  List<InspectionReportPhoto> get allPhotos =>
      allItems.expand((item) => item.photos).toList(growable: false);

  int get totalItemCount => allItems.length;
  int get flaggedItemCount => flaggedItems.length;
  int get atRiskCount => allItems
      .where((item) => item.conditionRating == ReportConditionRating.monitor)
      .length;
  int get unsatisfactoryCount => allItems
      .where(
        (item) => item.conditionRating == ReportConditionRating.unsatisfactory,
      )
      .length;
  int get criticalCount => allItems
      .where((item) => item.conditionRating == ReportConditionRating.critical)
      .length;
  int get photoCount => allPhotos.length;

  String get statusLabel => status.label;
}
